//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface NSImage (UXKit)
- (id)resizableImageWithCapInsets:(NSEdgeInsets)arg1 resizingMode:(NSInteger)arg2; // TODO: enum
- (id)resizableImageWithCapInsets:(NSEdgeInsets)arg1;
@end

