//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface UXBarItem : NSObject

@property (nonatomic) NSInteger tag;
@property (nonatomic, strong) NSImage *image;
@property (nonatomic, copy) NSString *accessibilityLabel;
@property (nonatomic, strong) NSString *title;
@property (nonatomic, getter=isEnabled) BOOL enabled;

@end

