//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXCollectionView, UXCollectionViewLayout;

@interface UXCollectionViewLayoutAccessibility : NSAccessibilityElement

+ (Class)sectionAccessibilityClass;
@property (nonatomic, weak) UXCollectionViewLayout *layout;
- (void)accessibilityPostNotification:(id)arg1;
@property (nonatomic, copy) NSArray *accessibilitySelectedCells; // @dynamic accessibilitySelectedCells;
- (id)accessibilityArrayAttributeValues:(id)arg1 index:(NSUInteger)arg2 maxCount:(NSUInteger)arg3;
- (NSUInteger)accessibilityArrayAttributeCount:(id)arg1;
- (NSUInteger)accessibilityIndexOfChild:(id)arg1;
- (CGRect)accessibilityFrameInParentSpace;
- (CGRect)accessibilityFrame;
- (id)accessibilityHitTest:(CGPoint)arg1;
- (id)nextSectionForSection:(id)arg1;
- (id)previousSectionForSection:(id)arg1;
- (id)accessibilityParentForCell:(id)arg1;
- (id)accessibilityParentForReusableView:(id)arg1;
- (void)accessibilityPrepareLayout;
- (void)accessibilityInvalidateLayout;
- (void)accessibilityDidEndScrolling;
- (void)accessibilityPrepareForCollectionViewUpdates:(id)arg1;
@property (nonatomic, weak, readonly) UXCollectionView *collectionView;
- (id)initWithLayout:(id)arg1;

@end

