//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface UXCollectionViewLayoutAttributes : NSObject <NSCopying>

+ (id)layoutAttributesForDecorationViewOfKind:(id)arg1 withIndexPath:(id)arg2;
+ (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 withIndexPath:(id)arg2;
+ (id)layoutAttributesForCellWithIndexPath:(id)arg1;
@property (nonatomic, strong) NSIndexPath *indexPath;
@property (nonatomic) BOOL isFloatingPinned;
@property (nonatomic) CGRect floatingFrame;
@property (nonatomic) BOOL isFloating;
@property (nonatomic) NSInteger zIndex;
@property (nonatomic) CGFloat alpha;
@property (nonatomic) CGSize size;
@property (nonatomic) CGPoint center;
@property (nonatomic, readonly) NSString *representedElementKind;
@property (nonatomic, readonly) NSUInteger representedElementCategory; // TODO: enum
@property (nonatomic) CGRect frame;
@property (nonatomic) CGRect bounds;
@property (nonatomic, getter=isHidden) BOOL hidden;

@end

