//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionViewLayout.h>

@interface UXCollectionViewFlowLayout : UXCollectionViewLayout

+ (Class)invalidationContextClass;
@property (nonatomic) NSEdgeInsets sectionInset;
@property (nonatomic) CGSize footerReferenceSize;
@property (nonatomic) CGSize headerReferenceSize;
@property (nonatomic) CGSize itemSize;
@property (nonatomic) CGFloat minimumInteritemSpacing;
@property (nonatomic) CGFloat minimumLineSpacing;
@property (nonatomic) NSInteger scrollDirection; // TODO: enum
- (id)layoutAttributesForElementsInRect:(CGRect)arg1;
- (id)indexPathsForItemsInRect:(CGRect)arg1;
- (BOOL)shouldUpdateVisibleCellLayoutAttributes;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForFooterInSection:(NSInteger)arg1;
- (id)layoutAttributesForHeaderInSection:(NSInteger)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1 usingData:(id)arg2;
- (id)layoutAttributesForFooterInSection:(NSInteger)arg1 usingData:(id)arg2;
- (id)layoutAttributesForHeaderInSection:(NSInteger)arg1 usingData:(id)arg2;
- (id)indexPathOfItemAfter:(id)arg1;
- (id)indexPathOfItemBefore:(id)arg1;
- (id)indexPathOfItemAbove:(id)arg1;
- (id)indexPathOfItemBelow:(id)arg1;
- (id)indexPathForItemAtPoint:(CGPoint)arg1;
- (id)indexesForSectionFootersInRect:(CGRect)arg1;
- (id)indexesForSectionHeadersInRect:(CGRect)arg1;
- (id)indexPathsForItemsInRect:(CGRect)arg1 usingData:(id)arg2;
- (id)indexesForSectionFootersInRect:(CGRect)arg1 usingData:(id)arg2;
- (id)indexesForSectionHeadersInRect:(CGRect)arg1 usingData:(id)arg2;
- (CGSize)collectionViewContentSize;
- (id)invalidationContextForBoundsChange:(CGRect)arg1;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1;
- (void)invalidateLayoutWithContext:(id)arg1;
- (CGSize)synchronizeLayout;
- (id)finalLayoutAttributesForFooterInDeletedSection:(NSInteger)arg1;
- (id)finalLayoutAttributesForHeaderInDeletedSection:(NSInteger)arg1;
- (id)finalLayoutAttributesForDeletedItemAtIndexPath:(id)arg1;
- (id)initialLayoutAttributesForFooterInInsertedSection:(NSInteger)arg1;
- (id)initialLayoutAttributesForHeaderInInsertedSection:(NSInteger)arg1;
- (id)initialLayoutAttributesForInsertedItemAtIndexPath:(id)arg1;
- (void)finalizeCollectionViewUpdates;

@end

