//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXBar.h>
#import <UXKit/UXNavigationControllerDelegate-Protocol.h>

@class UXNavigationItem;

@interface UXNavigationBar : UXBar

@property (nonatomic) BOOL recalculatingWindowKeyViewLoop;
@property (nonatomic, strong) UXNavigationItem *transitioningItem;
@property (nonatomic) NSInteger currentOperation; // TODO: enum
@property (nonatomic) CGFloat centerYOffset;
@property (nonatomic) CGFloat rightInteritemSpacing;
@property (nonatomic) CGFloat leftInteritemSpacing;
@property (nonatomic, getter=isDetached) BOOL detached;
@property (nonatomic) BOOL enableAlernateTitle;
@property (nonatomic, strong) NSView *alternateTitleView;
@property (nonatomic, strong) NSImage *backIndicatorImage;
@property (nonatomic, copy) NSArray *items;
@property (nonatomic, weak) NSView *titleCenteringTrackedView;
@property (nonatomic) NSEdgeInsets edgeInsets;
@property (nonatomic, getter=isTranslucent) BOOL translucent;
@property (nonatomic, weak) id <UXNavigationBarDelegate> delegate;
- (void)setNeedsRecalcuateWindowKeyViewLoop;
- (void)recalculateKeyViewLoop;
- (void)beginInteractivePop;
- (void)beginInteractivePushToItem:(id)arg1;
- (id)popNavigationItemAnimated:(BOOL)arg1;
- (void)pushNavigationItem:(id)arg1 animated:(BOOL)arg2;
@property (nonatomic, readonly) UXNavigationItem *backItem;
@property (nonatomic, readonly) UXNavigationItem *topItem;
- (NSInteger)barPosition; // TODO: enum

@end

