//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UXKit/UXCollectionViewController.h>

@class UXTableView;

@interface UXTableViewController : UXCollectionViewController

+ (Class)collectionViewClass;
@property (nonatomic, readonly) id <UXTableViewDelegate> tableViewDelegate;
@property (nonatomic, readonly) UXTableView *tableView;
- (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil NS_DESIGNATED_INITIALIZER;
- (instancetype)initWithStyle:(NSInteger)arg1; // TODO: enum


@end
