//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionViewCell.h>

@class UXLabel, UXView;

@interface UXTableViewCell : UXCollectionViewCell

@property (nonatomic) NSEdgeInsets separatorInset;
@property (nonatomic) CGFloat indentationWidth;
@property (nonatomic) NSInteger indentationLevel; // TODO: enum
@property (nonatomic) NSInteger selectionStyle; // TODO: enum
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic, strong) NSColor *highlightColor;
@property (nonatomic, strong) UXView *accessoryView;
@property (nonatomic) NSInteger accessoryType; // TODO: enum
@property (nonatomic, strong) UXLabel *detailTextLabel;
@property (nonatomic, strong) UXLabel *textLabel;
@property (nonatomic, strong) UXView *selectedBackgroundView;
@property (nonatomic, strong) UXView *backgroundView;
@property (nonatomic) NSInteger style; // TODO: enum
@property (nonatomic, readonly) UXView *lowerSpace;
@property (nonatomic, readonly) UXView *upperSpace;
@property (nonatomic, readonly) UXView *defaultSelectedBackgroundView;

- (instancetype)initWithFrame:(CGRect)arg1 NS_DESIGNATED_INITIALIZER;
- (instancetype)initWithStyle:(NSInteger)arg1 reuseIdentifier:(NSString *)arg2 NS_DESIGNATED_INITIALIZER; // TODO: enum

@end

