//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface NSView (Compatibility)
- (void)setContentCompressionResistancePriority:(NSLayoutPriority)arg1 forAxis:(NSLayoutConstraintOrientation)arg2;
- (NSLayoutPriority)contentCompressionResistancePriorityForAxis:(NSLayoutConstraintOrientation)arg1;
- (void)setContentHuggingPriority:(NSLayoutPriority)arg1 forAxis:(NSLayoutConstraintOrientation)arg2;
- (NSLayoutPriority)contentHuggingPriorityForAxis:(NSLayoutConstraintOrientation)arg1;
@property (nonatomic) CGFloat alpha;
- (BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutIfNeeded;
- (void)layoutSubviews;
- (void)setNeedsUpdateConstraints;
- (void)updateConstraintsIfNeeded;
- (void)setNeedsDisplay;
- (void)setNeedsLayout;
- (void)didMoveToWindow;
@property (nonatomic, readonly, getter=isHidden) BOOL hidden;
@end

