//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXView.h>
#import <UXKit/UXBarPositioning-Protocol.h>

@interface UXBar : UXView <NSAccessibilityGroup, UXBarPositioning>

@property (nonatomic, strong) UXView *nextItemContainer;
@property (nonatomic) CGFloat percent;
@property (nonatomic) BOOL isInteractiveTransitioning;
@property (nonatomic, strong) UXView *barItemsContainer;
@property (nonatomic) CGFloat height;
@property (nonatomic) CGFloat interitemSpacing;
@property (nonatomic, strong) NSColor *barTintColor;
@property (nonatomic, readonly) NSInteger barPosition; // TODO: enum
@property (nonatomic, strong) NSColor *borderColor;
@property (nonatomic) BOOL bordered;

@end

