//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionReusableView.h>

@interface UXCollectionViewCell : UXCollectionReusableView

@property (nonatomic, readonly) NSView *contentView;
@property (nonatomic, getter=isSelected) BOOL selected;

@end

