//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXView.h>

@interface UXImageView : UXView <NSAccessibilityImage>

@property (nonatomic, strong) NSImage *image;
@property (nonatomic, strong) NSString *accessibilityLabel;
- (instancetype)initWithImage:(NSImage *)arg1 NS_DESIGNATED_INITIALIZER;
- (instancetype)initWithFrame:(CGRect)arg1 NS_DESIGNATED_INITIALIZER;

@end

