//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXBarItem.h>

@interface UXTabBarItem : UXBarItem

@property (nonatomic, copy) NSSet *possibleTitles;
- (instancetype)initWithTitle:(NSString *)arg1;

@end

