//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UXKit/UXCollectionView.h>

#import <UXKit/_UXCollectionViewOverdraw-Protocol.h>

@class NSString;

@interface _UXCollectionView : UXCollectionView <_UXCollectionViewOverdraw>
{
}

+ (Class)documentClass;
@property(nonatomic) BOOL overdrawEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

