//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UXKit/UXView.h>

#import <UXKit/UXLayoutSupport-Protocol.h>

@class NSLayoutConstraint, NSString;

@interface _UXLayoutGuide : UXView <UXLayoutSupport>
{
    NSLayoutConstraint *_counterDimensionConstraint;
    NSLayoutConstraint *_dimensionConstraint;
    BOOL _horizontal;
    id _lengthUpdateBlock;
}

@property(copy, nonatomic) id lengthUpdateBlock; // @synthesize lengthUpdateBlock=_lengthUpdateBlock;
@property(nonatomic) BOOL horizontal; // @synthesize horizontal=_horizontal;

- (void)_setUpDimensionConstraintWithLength:(double)arg1;
- (void)_setUpCounterDimensionConstraint;
@property(nonatomic) double length;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

