//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSColor;

@protocol UXKitAppearance <NSObject>
@property(nonatomic) long long tintAdjustmentMode;
@property(retain, nonatomic) NSColor *tintColor;
- (void)tintColorDidChange;
@end

