//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UXKit/UXViewController.h>

@class UXView;

@interface UXProxyViewController : UXViewController
{
    UXView *_proxyView;
}


- (void)didMoveToParentViewController:(id)arg1;
- (BOOL)isViewLoaded;
- (id)view;
- (id)initWithView:(id)arg1;

@end

