//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface NSGestureRecognizer (UXKit)
- (void)setGestureDidEndHandler:(void (^)(id /* NSGestureRecognizer* */))arg1;
- (void)setGestureDidChangeHandler:(void (^)(id /* NSGestureRecognizer* */))arg1;
- (void)setGestureDidBeginHandler:(void (^)(id /* NSGestureRecognizer* */))arg1;
@end

