//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface NSTextField (Compatibility) <UITextInputTraits>
@property (nonatomic) NSUInteger textAlignment; // TODO: enum
@property (nonatomic, copy) NSString *placeholder;
@property (nonatomic, copy) NSString *text;
@property (nonatomic) NSInteger autocapitalizationType; // TODO: enum
@property (nonatomic) NSInteger autocorrectionType; // TODO: enum
@property (nonatomic) BOOL enablesReturnKeyAutomatically;
@property (nonatomic) NSInteger keyboardAppearance; // TODO: enum
@property (nonatomic) NSInteger keyboardType; // TODO: enum
@property (nonatomic) NSInteger returnKeyType; // TODO: enum
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property (nonatomic) NSInteger spellCheckingType; // TODO: enum
@end

