//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UXKit/UXCollectionViewIndexPathsSet.h>

@interface UXCollectionViewMutableIndexPathsSet : UXCollectionViewIndexPathsSet

- (void)adjustForDeletionOfIndexPath:(id)arg1;
- (void)adjustForDeletionOfItems:(id)arg1 inSection:(NSUInteger)arg2;
- (void)adjustForInsertionOfIndexPath:(id)arg1;
- (void)adjustForInsertionOfItems:(id)arg1 inSection:(NSUInteger)arg2;
- (void)adjustForDeletionOfSections:(id)arg1;
- (void)adjustForDeletionOfSection:(NSUInteger)arg1;
- (void)adjustForInsertionOfSections:(id)arg1;
- (void)adjustForInsertionOfSection:(NSUInteger)arg1;
- (void)intersectIndexPathsSet:(id)arg1;
- (void)removeAllIndexPaths;
- (void)removeIndexPathsSet:(id)arg1;
- (void)removeIndexPaths:(id)arg1;
- (void)removeIndexPath:(id)arg1;
- (void)addSection:(NSInteger)arg1 itemsInRange:(NSRange)arg2;
- (void)addIndexPathsSet:(id)arg1;
- (void)addIndexPaths:(id)arg1;
- (void)addIndexPath:(id)arg1;

@end

