//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXEventTracker.h>

@interface UXPinchEventTracker : UXEventTracker

@property (nonatomic) CGFloat scale;
- (CGPoint)locationOfTouch:(NSUInteger)arg1 inView:(id)arg2; // TODO: type
- (CGPoint)locationOfTouch:(id)arg1;
- (CGPoint)locationInView:(id)arg1;

@end

