//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXViewController.h>

@interface UXTabBarController : UXViewController

@property (nonatomic, readonly) NSSegmentedControl *segmentedControl;
@property (nonatomic, weak) UXViewController *selectedViewController;
@property (nonatomic, copy) NSArray *viewControllers;
@property (nonatomic) NSUInteger selectedIndex;

@end

