//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface NSProgressIndicator (Compatibility)
- (BOOL)isAnimating;
- (void)stopAnimating;
- (void)startAnimating;
@property (nonatomic, strong) NSColor *color;
@property (nonatomic) BOOL hidesWhenStopped;
@property (nonatomic) NSInteger activityIndicatorViewStyle; // TODO: enum
- (void)setProgress:(double)arg1 animated:(BOOL)arg2;
@property (nonatomic) double progress;
@property (nonatomic) NSInteger progressViewStyle; // TODO: enum
- (instancetype)initWithProgressViewStyle:(NSInteger)arg1; // TODO: enum
- (instancetype)initWithActivityIndicatorStyle:(NSInteger)arg1; // TODO: enum
@end

