//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@protocol UITextInputTraits <NSObject>

@optional
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property (nonatomic) BOOL enablesReturnKeyAutomatically;
@property (nonatomic) NSInteger returnKeyType; // TODO: enum
@property (nonatomic) NSInteger keyboardAppearance; // TODO: enum
@property (nonatomic) NSInteger keyboardType; // TODO: enum
@property (nonatomic) NSInteger spellCheckingType; // TODO: enum
@property (nonatomic) NSInteger autocorrectionType; // TODO: enum
@property (nonatomic) NSInteger autocapitalizationType; // TODO: enum
@end

