//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXCollectionViewLayoutAttributes;

@interface UXCollectionReusableView : NSView

@property (nonatomic, copy, readonly) NSString *reuseIdentifier;
@property (nonatomic, readonly) BOOL isFloatingPinned;
- (void)didTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (void)willTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (void)applyLayoutAttributes:(UXCollectionViewLayoutAttributes *)arg1;
- (void)prepareForReuse;

@end

