//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionViewLayout.h>
#import <UXKit/UXCollectionViewDelegate-Protocol.h>
#import <UXKit/UXCollectionViewDataSource-Protocol.h>

@interface UXCollectionView : NSScrollView

@property (nonatomic, readonly, getter=isDecelerating) BOOL decelerating;
@property (nonatomic, readonly, getter=isScrolling) BOOL scrolling;
@property (nonatomic) BOOL allowsPaintingSelection;
@property (nonatomic) BOOL allowsLassoSelection;
@property (nonatomic) BOOL allowsContinuousSelection;
@property (nonatomic, strong) UXCollectionViewLayout *collectionViewLayout;
- (BOOL)accessibilityPerformPressWithItemAtIndexPath:(id)arg1;
- (id)accessibilityContentSiblingCellFromIndexPath:(id)arg1 direction:(id)arg2;
- (void)accessibilitySelectItemsAtIndexPaths:(id)arg1;
- (void)accessibilitySelected:(BOOL)arg1 itemAtIndexPath:(id)arg2;
- (void)performBatchUpdates:(void(^)(void))arg1 completion:(void(^)(BOOL finished))arg2;
- (void)moveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)reloadItemsAtIndexPaths:(id)arg1;
- (void)deleteItemsAtIndexPaths:(id)arg1;
- (void)insertItemsAtIndexPaths:(id)arg1;
- (void)moveSection:(NSInteger)arg1 toSection:(NSInteger)arg2;
- (void)reloadSections:(id)arg1;
- (void)deleteSections:(id)arg1;
- (void)insertSections:(id)arg1;
- (void)scrollRect:(CGRect)arg1 toScrollPosition:(NSUInteger)arg2 withInsets:(NSEdgeInsets)arg3 animated:(BOOL)arg4; // TODO: enum
- (void)scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(NSUInteger)arg2 animated:(BOOL)arg3; // TODO: enum
- (id)contentSupplementaryViews;
- (id)visibleSupplementaryViews;
- (id)indexPathsForContentItemsInSections:(id)arg1;
- (id)indexPathsForContentItems;
- (id)indexPathsForVisibleItemsInSections:(id)arg1;
- (id)indexPathsForVisibleItems;
- (id)contentCells;
- (id)visibleCells;
- (NSUInteger)numberOfContentCells;
- (NSUInteger)numberOfVisibleCells;
- (id)viewForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)cellForItemAtIndexPath:(id)arg1;
- (id)indexPathForSupplementaryView:(id)arg1;
- (id)indexPathForCell:(id)arg1;
- (id)indexPathForSupplementaryElementOfKind:(id)arg1 atPoint:(CGPoint)arg2;
- (id)indexPathForSupplementaryElementOfKind:(id)arg1 hitByEvent:(id)arg2;
- (id)indexPathForItemAtPoint:(CGPoint)arg1;
- (id)indexPathForItemHitByEvent:(id)arg1;
- (id)layoutAttributesForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (NSInteger)numberOfItemsInSection:(NSInteger)arg1;
- (NSInteger)numberOfSections;
- (CGRect)documentContentRect;
- (void)setCollectionViewLayout:(id)arg1 animated:(BOOL)arg2 completion:(void(^)(BOOL finished))arg3;
- (void)setCollectionViewLayout:(id)arg1 animated:(BOOL)arg2;
- (id)dequeueReusableSupplementaryViewOfKind:(id)arg1 withReuseIdentifier:(id)arg2 forIndexPath:(id)arg3;
- (id)dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (void)registerNib:(id)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)registerClass:(Class)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)registerNib:(id)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)registerClass:(Class)arg1 forCellWithReuseIdentifier:(id)arg2;
- (CGSize)contentSizeForFrameSize:(CGSize)arg1;
- (CGSize)frameSizeForContentSize:(CGSize)arg1;
- (void)setContentOffset:(CGPoint)arg1 animated:(BOOL)arg2;
@property (atomic, readwrite) CGSize contentSize;
- (CGSize)documentSize;
- (CGPoint)contentOffset;
- (void)reloadData;
@property (nonatomic) BOOL allowsEmptySelection;
@property (nonatomic) BOOL allowsMultipleSelection;
@property (nonatomic) BOOL allowsSelection;
- (void)deselectAllItems:(BOOL)arg1;
- (void)selectAllItems:(BOOL)arg1;
- (void)deselectItemsAtIndexPaths:(id)arg1 animated:(BOOL)arg2;
- (void)deselectItemAtIndexPath:(id)arg1 animated:(BOOL)arg2;
- (void)selectItemsAtIndexPaths:(id)arg1 byExtendingSelection:(BOOL)arg2 animated:(BOOL)arg3 scrollItemAtIndex:(id)arg4 toPosition:(NSUInteger)arg5; // TODO: enum
- (void)selectItemsAtIndexPaths:(id)arg1 byExtendingSelection:(BOOL)arg2 animated:(BOOL)arg3;
- (void)selectItemAtIndexPath:(id)arg1 animated:(BOOL)arg2 scrollPosition:(NSUInteger)arg3; // TODO: enum
- (BOOL)selectedItemAtIndexPath:(id)arg1;
- (BOOL)selectableItemAtIndexPath:(id)arg1;
- (NSUInteger)numberOfSelectedItems;
- (id)indexPathsForSelectedItems;
@property (nonatomic, weak) id<UXCollectionViewDataSource> dataSource;
@property (nonatomic, weak) id<UXCollectionViewDelegate> delegate;

- (id)initWithFrame:(CGRect)arg1 collectionViewLayout:(id)arg2 NS_DESIGNATED_INITIALIZER;

@end

