//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXCollectionView;

@protocol UXCollectionViewAccessibilityDelegate <NSObject>

@optional
- (void)collectionView:(UXCollectionView *)arg1 shouldPrepareAccessibilitySection:(id <NSAccessibility>)arg2;
- (NSString *)collectionViewAccessibilityRoleDescription:(UXCollectionView *)arg1;
@end

