//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXView;

@interface UXEventTracker : NSResponder

@property (nonatomic, copy) void(^eventTrackerDidBeginHandler)(id /*UXEventTracker*/);
@property (nonatomic, copy) void(^eventTrackerDidChangeHandler)(id /*UXEventTracker*/);
@property (nonatomic, copy) void(^eventTrackerDidEndHandler)(id /*UXEventTracker*/);
@property (nonatomic, getter=isEnabled) BOOL enabled;
@property (nonatomic) BOOL cancelsEventsInView;
@property (nonatomic) NSUInteger ignoredModifiers; // TODO: enum
@property (nonatomic) CGFloat velocity;
@property (nonatomic) NSUInteger modifiers; // TODO: enum
@property (nonatomic, strong) NSEvent *trackingEvent;
@property (nonatomic, weak) UXView *view;
@property (nonatomic) NSInteger state; // TODO: enum
@property (nonatomic, readonly) NSUInteger numberOfTouches;
- (CGPoint)locationOfTouch:(NSUInteger)arg1 inView:(id)arg2; // TODO: type
- (CGPoint)locationInView:(id)arg1;
- (void)cancelTracking;
- (void)removeTarget:(id)arg1;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

