//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXAuxiliaryNavigationStore;

@protocol UXNavigationDestination <NSObject, NSSecureCoding>
@property (nonatomic, readonly) UXAuxiliaryNavigationStore *auxiliaryNavigationStore;
@property (nonatomic, readonly) NSString *destinationTitle;
@property (nonatomic, readonly) NSString *destinationType;
@end

