//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXViewController.h>
#import <UXKit/UXToolbarDelegate-Protocol.h>

@class UXEventTracker, UXNavigationBar, UXToolbar;

@interface UXNavigationController : UXViewController <UXToolbarDelegate>

@property (nonatomic, readonly) UXEventTracker *interactivePopEventTracker;
@property (nonatomic, weak) id <UXNavigationControllerDelegate> delegate;
@property (nonatomic, getter=isToolbarHidden) BOOL toolbarHidden;
@property (nonatomic, getter=isNavigationBarDetached) BOOL navigationBarDetached;
@property (nonatomic, getter=isNavigationBarHidden) BOOL navigationBarHidden;
- (id)visibleViewController;
- (id)topViewController;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (id)popToRootViewControllerAnimated:(BOOL)arg1;
- (id)popToViewController:(id)arg1 animated:(BOOL)arg2;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)setViewControllers:(id)arg1 animated:(BOOL)arg2;
- (void)detachNavigationBar;
@property (nonatomic, readonly) UXToolbar *toolbar;
@property (nonatomic, readonly) UXNavigationBar *navigationBar;
- (void)setToolbarHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setNavigationBarHidden:(BOOL)arg1 animated:(BOOL)arg2;
@property (nonatomic, copy) NSArray *viewControllers;

- (instancetype)initWithRootViewController:(id)arg1;

@end

