//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UXKit/UXViewController.h>

@protocol UXPopoverControllerDelegate;

@interface UXPopoverController : UXViewController <NSPopoverDelegate>

@property (nonatomic, copy) NSArray *passthroughViews;
@property (nonatomic, weak) id <UXPopoverControllerDelegate> delegate;
- (void)dismissPopoverAnimated:(BOOL)arg1;
- (void)dismissPopover;
- (void)presentPopoverFromBarButtonItem:(id)arg1 permittedArrowDirections:(NSUInteger)arg2 animated:(BOOL)arg3; // TODO: enum
- (void)presentPopoverFromRect:(CGRect)arg1 inView:(id)arg2 preferredEdge:(NSUInteger)arg3; // TODO: enum
@property (nonatomic, strong) UXViewController *contentViewController;
@property (nonatomic) CGSize popoverContentSize;
- (void)setPopoverContentSize:(CGSize)arg1 animated:(BOOL)arg2;
@property (nonatomic, readonly, getter=isPopoverVisible) BOOL popoverVisible;
@property (nonatomic) NSInteger popoverBehavior;  // TODO: enum
- (id)initWithContentViewController:(id)arg1;

@end

@protocol UXPopoverControllerDelegate <NSObject>
@optional

- (void)popoverController:(UXPopoverController *)popoverController willRepositionPopoverToRect:(inout CGRect *)rect inView:(inout UXView **)view;
- (BOOL)popoverControllerShouldDismissPopover:(UXPopoverController *)popoverController;
- (void)popoverControllerDidDismissPopover:(UXPopoverController *)popoverController;

@end
