//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@protocol UXViewControllerInteractiveTransitioning <NSObject>
- (void)startInteractiveTransition:(id <UXViewControllerContextTransitioning>)arg1;

@optional
- (NSInteger)completionCurve; // TODO: enum
- (CGFloat)completionSpeed;
@end

