//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface UXView : NSView

+ (void)animateWithDuration:(CGFloat)arg1 delay:(CGFloat)arg2 usingSpringWithDamping:(CGFloat)arg3 initialSpringVelocity:(CGFloat)arg4 options:(NSUInteger)arg5 animations:(void(^)(void))arg6 completion:(void(^)(BOOL finished))arg7; // TODO
+ (void)animateWithDuration:(CGFloat)arg1 animations:(void(^)(void))arg2;
+ (void)animateWithDuration:(CGFloat)arg1 animations:(void(^)(void))arg2 completion:(void(^)(BOOL finished))arg3;
+ (void)animateWithDuration:(CGFloat)arg1 delay:(CGFloat)arg2 options:(NSInteger)arg3 animations:(void(^)(void))arg4 completion:(void(^)(BOOL finished))arg5; // TODO: enum
+ (Class)layerClass;
@property (nonatomic) BOOL accessibilityChildrenHidden;
@property (nonatomic) BOOL userInteractionEnabled;
@property (nonatomic, getter=isExclusiveTouch) BOOL exclusiveTouch;
- (id)accessibilityChildren;
- (id)snapshotViewFromRect:(CGRect)arg1;
- (id)snapshotView;
- (id)snapshotForRect:(CGRect)arg1;
- (void)sendSubviewToBack:(id)arg1;
- (void)bringSubviewToFront:(id)arg1;
@property (nonatomic, readonly) CGPoint center;
@property (nonatomic, readonly) NSArray *eventTrackers;
- (void)removeEventTracker:(id)arg1;
- (void)addEventTracker:(id)arg1;
- (BOOL)isInResponderChainOf:(id)arg1;
@property (nonatomic) NSInteger contentMode; // TODO: enum
@property (nonatomic) BOOL blurEnabled;

@end

