//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXViewController, UXNavigationController;

@interface UXWindowController : NSWindowController <NSToolbarDelegate, NSWindowDelegate>

+ (NSWindow *)defaultWindow;

- (instancetype)initWithRootViewController:(UXViewController *)arg1 NS_DESIGNATED_INITIALIZER;

@property (weak) NSToolbarItem *navigationBarToolbarItem;
@property (nonatomic, strong) UXViewController *rootViewController;
@property (nonatomic, readonly) NSTitlebarAccessoryViewController *titlebarAccessoryViewController;
@property (nonatomic, readonly) UXNavigationController *rootNavigationController;

@end
