//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, UXViewController;

@interface _UXNavigationRequest : NSObject
{
    BOOL _animated;
    long long _operation;
    NSArray *_viewControllers;
}

+ (id)setRequestWithViewControllers:(id)arg1 animated:(BOOL)arg2;
+ (id)popRequestWithViewController:(id)arg1 animated:(BOOL)arg2;
+ (id)pushRequestWithViewController:(id)arg1 animated:(BOOL)arg2;
+ (id)_requestWithOperation:(long long)arg1 viewControllers:(id)arg2 animated:(BOOL)arg3;
@property(readonly, nonatomic) BOOL animated; // @synthesize animated=_animated;
@property(readonly, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(readonly, nonatomic) long long operation; // @synthesize operation=_operation;

@property(readonly, nonatomic) UXViewController *viewController;

@end

