//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UXKit/UXCollectionReusableView.h>

@class NSBox, UXLabel, UXView;

@interface _UXTableHeaderView : UXCollectionReusableView
{
    BOOL _floating;
    UXView *_contentView;
    UXLabel *_titleLabel;
    NSBox *_separator;
}

@property(readonly, nonatomic) NSBox *separator; // @synthesize separator=_separator;
@property(readonly, nonatomic) UXLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) UXView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic, getter=isFloating) BOOL floating; // @synthesize floating=_floating;

- (void)mouseDown:(id)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

