//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSGestureRecognizer.h>

@interface NSGestureRecognizer (UXKit)
- (void)__stateChange:(id)arg1;
- (void)setGestureDidEndHandler:(id)arg1;
- (void)setGestureDidChangeHandler:(id)arg1;
- (void)setGestureDidBeginHandler:(id)arg1;
@end

