//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UXKit/UXTransitionController.h>

@interface UXIdentityTransitionController : UXTransitionController
{
}

- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

@end

