//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  5 2015 02:41:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, UXView, UXViewController;

@protocol UXViewControllerTransitionCoordinatorContext <NSObject>
- (UXView *)containerView;
- (UXViewController *)viewControllerForKey:(NSString *)arg1;
- (long long)completionCurve;
- (double)completionVelocity;
- (double)percentComplete;
- (double)transitionDuration;
- (BOOL)isCancelled;
- (BOOL)isInteractive;
- (BOOL)initiallyInteractive;
- (long long)presentationStyle;
- (BOOL)isAnimated;
@end

